name: CI/CD Update abi

on:
  push:
    branches: 
      - main
      - add-workflow
jobs:
  update:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Update abi
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:    
          source-files: 'data/abi/Irrigation.json'
          destination-username: 'ruymaster'
          destination-repository: 'IrrigationProtocol/irrigation-dapp'
          destination-directory: 'src/config/abi'
          commit-email:  ${{ secrets.DEV_MAIL }}
