name: CI/CD Update abi

on:
  push:
    branches:
      - main
      - develop
jobs:
  update-ui:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Update UI
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: "data/"
          destination-repository: "IrrigationProtocol/irrigation-dapp"
          destination-branch: "develop"
          destination-directory: "src/config"
          commit-email: ${{ secrets.DEV_MAIL }}
          commit-username: "ruymaster"
  update-subgraph:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Update Subgraph
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: "data/abi/Irrigation.json"
          destination-repository: "IrrigationProtocol/irrigation-subgraph"
          destination-branch: "develop"
          destination-directory: "abis"
          commit-email: ${{ secrets.DEV_MAIL }}
          commit-username: "ruymaster"
